on: 
    push:
        branches:    
            - develop
            - master   
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: https://hooks.slack.com/services/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